bayes_people_tracker:
  # The Kalman filter type: EKF = Extended Kalman Filter, UKF = Uncented Kalman Filter
  filter_type: "UKF"
  # The noise for the constant velocity prediction model
  cv_noise_params:
      x: 5.0
      y: 5.0
  # Add detectors under this namespace
  detectors:
    # Name of detector (used internally to identify them). Has to be unique.
    clusterer:
        # The topic on which the geometry_msgs/PoseArray is published
        topic: "/cluster_centers"
        # The noise for the cartesian observation model
        cartesian_noise_params:
            x: 0.3
            y: 0.3
        # The algorthim to match different detections. NN = Nearest Neighbour, NNJPDA = NN Joint Probability Data Association
        matching_algorithm: "NNJPDA"
